/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  email: string;
  image?: string;
  motDePasse: string;
  nom: string;
  phoneNumber: string;
  prenom: string;
  roles?: 'Entrepreneur' | 'Student' | 'Admin';
}
