/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email: string;
  enabled?: boolean;
  idUser?: number;
  image?: string;
  lastModifiedDate?: string;
  motDePasse?: string;
  name?: string;
  nom?: string;
  password?: string;
  phoneNumber: string;
  prenom?: string;
  roles?: 'Entrepreneur' | 'Student' | 'Admin';
  username?: string;
}
