/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthentificationService } from './services/authentification.service';
export { FacialRecognitionControllerService } from './services/facial-recognition-controller.service';
export { UserControllerService } from './services/user-controller.service';
